---

# Provision virtual machine example

- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - secrets.yml

  tasks:

    - command: azure group create linux-test-group "East US"

    - command: azure vm quick-create linux-test-group linux-single-machine "East US" linux OpenLogic:CentOS:7.1:7.1.20150731 azureuser {{ admin_user_password }}
 
    
    
