---

# Provision virtual machine example

- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - secrets.yml

  tasks:

    - command: azure group -y delete linux-test-group

